### ISSUE TITLE
Drumon Dando erro com Internet Explorer 7 a 9 version.

### ISSUE THREAD

**Issue by pragmaticivan** [sook/drumon_framework#7]
Dando erro 404 em qualquer cota .. inclusive na principal ao entrar no site n demora nem 1 segundo. e da erro. testei o .htaccess tirando a penultima linha ele parou de fazer esse erro de 404 mais a linha era necessária para as rotas.

**Comment by danillos** [comment]
Testei no ie8, em sites localhost e nos sites que uso o drumon em produção, e abriu todos os sites perfeitamente.

Preciso de mais detalhes.

**Comment by pragmaticivan** [comment]
maceio40graus.com.br

http://redealagoas.com.br/
testa ai ...

**Comment by danillos** [comment]
Abriu aqui,

http://bit.ly/mBUFG4
http://dl.dropbox.com/u/131777/Screenshots/%7Ekhf.png

como você fez esses testes?

On Sat, Jun 11, 2011 at 1:19 PM, ivansjr <
reply@reply.github.com>wrote:

> maceio40graus.com.br
> 
> http://redealagoas.com.br/
> testa ai ...
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sook/drumon_framework/issues/7#issuecomment-1351099

## 

---

Danillo César de O. Melo - blog http://www.danillocesar.com.br |
twitterhttp://twitter.com/danillos

Sook - http://www.sook.com.br

**Comment by danillos** [comment]
Inválido: Front-end não interfere no back-end.
