### ISSUE TITLE
Problema usando uma porta diferente da 80.

### ISSUE THREAD

**Issue by emersonpgomes** [sook/drumon_framework#9]
Pessoal, estou usando o Drumon aqui em um projeto e tive problemas usando uma porta diferente da porta 80 do http. O problema é que o Drumon não carrega o CSS nem coloca a porta nos links gerado pelo $html->link. 

Para fazer o meu projeto funcionar corretamente, eu alterei o arquivo app.php, em  vendor\drumon_core\class\, modificando a linha que tem:

> $app->config['app_domain'] = App::remove_last_slash('http://' . $_SERVER['SERVER_NAME'] . dirname($_SERVER['SCRIPT_NAME']));

para: 

> $app->config['app_domain'] = App::getAppDomain();

e criei o metodo:

> public static function getAppDomain() {
>             if($_SERVER['SERVER_PORT'] == '80'){
>                     $domain = $_SERVER['SERVER_NAME'] . dirname($_SERVER['SCRIPT_NAME']);
>                 }
>             else {
>                     $domain = $_SERVER['SERVER_NAME'] . ':' . $_SERVER['SERVER_PORT'] . dirname($_SERVER['SCRIPT_NAME']);
>                 }
>             return App::remove_last_slash('http://' . $domain);
>         }

Alguma outra forma de se fazer isso?

Emerson P. Gomes

**Comment by danillos** [comment]
Emerson,

Nunca tinha me deparado com esse problema, o jeito que você implementou está correto sim.

Gostaria muito da sua contribuição com essa correção dando um Pull Request para o repositório.

Agora um observação sobre essa implementação. 

Como esse código não está no repositório, o correto seria configurar na sua aplicação dependendo do ambiente em que sua aplicação está rodando.

Se a porta for diferente de 80 no servidor de produção, em: **/config/enviroments/production.php**
tem exatamente essa configuração comentada, para quem precisar altera-la.

Essa alteração pode ser feita em **production.php** / **development.php**

Dessa maneira quando sair uma nova versão do Drumon, você poderá atualizar  seu core sem problemas de quebrar sua aplicação.

Obrigado pelo Feedback.

**Comment by emersonpgomes** [comment]
Boa observação Danillo, eu não tinha pensado na atualização do core, nem notado que podia fazer isso no arquivo de configuração do ambiente. 

A minha necessidade inicial de modificar dessa forma se deve ao fato do projeto que estou desenvolvendo ser colaborativo e visa ser implantado em diversos clientes. Por isso quis uma forma que fosse mais automática.
